# Copyright (C) 2021  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier:ISC

name: FPGA interchange CI tests

on: [push, pull_request]

jobs:
  Run-Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - {test: "counter"}
          - {test: "lut"}
          - {test: "ram"}
          - {test: "wire"}

    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/setup-python@v2

    - uses: SymbiFlow/actions/checks@main

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install git make cmake

    - name: Cache environment
      id: cache-env
      uses: actions/cache@v2
      with:
        path: env
        key: env-${{ hashFiles('**/environment.yml', '**/requirements.txt') }}

    - name: Create environment
      if: steps.cache-env.outputs.cache-hit != 'true'
      run: make env

    - name: Build CMake
      run: make build

    - name: Run tests
      run: |
        source env.sh
        cd build
        make all-${{ matrix.test }}-tests -j`nproc`
